name: 'Hello World'
description: 'Greet someone'

inputs:
  action_input: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

runs:
  using: "composite"
  steps:
  - name: Set Greeting
    run: echo "action_input ${{ inputs.action_input }}"
    shell: bash

  - name: Set GitHub Path
    run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
    shell: bash
    env:
      GITHUB_ACTION_PATH: ${{ github.action_path }}

  - name: Run script
    run: script.sh
    shell: bash

  - name: call make
    run: make process_input ${{ github.action_path }}
    shell: bash
